// <auto-generated />
namespace Examiner.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Domainmodels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Domainmodels));
        
        string IMigrationMetadata.Id
        {
            get { return "201805021621195_Domain models"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
